export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS"
export const GET_EVENT_FAILED = "GET_EVENT_FAILED"

export const GET_EVENT_DETAIL_SUCCESS = "GET_EVENT_DETAIL_SUCCESS"
export const GET_EVENT_DETAIL_FAILED = "GET_EVENT_DETAIL_FAILED"

export const ATTEND_EVENT_SUCCESS = "ATTEND_EVENT_SUCCESS"
export const ATTEND_EVENT_FAILED = "ATTEND_EVENT_FAILED"

export const WITHDRAW_EVENT_SUCCESS = "WITHDRAW_EVENT_SUCCESS"
export const WITHDRAW_EVENT_FAILED = "WITHDRAW_EVENT_FAILED"

export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAILED = "GET_ALL_USER_FAILED"