export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS"
export const GET_EVENT_FAILED = "GET_EVENT_FAILED"

export const GET_EVENT_DETAIL_SUCCESS = "GET_EVENT_DETAIL_SUCCESS"
export const GET_EVENT_DETAIL_FAILED = "GET_EVENT_DETAIL_FAILED"